In [2]:
import numpy as np
import pickle
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import csv

In [3]:
dataset = pd.read_csv('heartt.csv')
X= dataset.iloc[:,:-1].values
Y= dataset.iloc[:,-1].values

In [4]:
dataset

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [6]:
X.shape

(1025, 13)

In [7]:
Y.shape

(1025,)

In [8]:

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [9]:
print(X_train)

[[42.  1.  3. ...  2.  2.  2.]
 [66.  0.  2. ...  1.  1.  2.]
 [53.  1.  2. ...  2.  3.  2.]
 ...
 [65.  1.  3. ...  1.  1.  2.]
 [67.  1.  0. ...  1.  0.  2.]
 [60.  1.  2. ...  1.  0.  2.]]


In [10]:
print(Y_test)

[1 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 0 0
 0 1 1 0 1 1 1 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0
 0 0 0 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 1 1 1 0 0 0 1 1 1 1 1 0 0 1 0 1 0 1 1
 0 1 0 1 0 1 0 0 1 0 1 1 0 0 1 1 1 1 0 0 0 1 1 1 0 0 1 0 1 1 0 1 0 0 1 1 1
 1 0 1 1 1 0 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 1 0 0 1
 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 1 1 0 1]


In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [12]:
print(X_test)

[[-1.03300622  0.71228712  1.09476414 ...  1.10494968 -0.69359871
  -0.55300244]
 [ 0.47193177 -1.40392824  0.09731237 ...  1.10494968  1.36709311
  -0.55300244]
 [ 1.00940963  0.71228712 -0.9001394  ...  1.10494968  1.36709311
   1.04369474]
 ...
 [-1.14050179 -1.40392824  1.09476414 ... -0.46806896 -0.69359871
  -0.55300244]
 [ 1.33189634 -1.40392824 -0.9001394  ... -0.46806896  1.36709311
   1.04369474]
 [ 1.86937419 -1.40392824 -0.9001394  ... -0.46806896 -0.69359871
  -0.55300244]]


In [13]:
print(X_train)

[[-1.40503359  0.64895597  1.97748631 ...  0.97028605  1.17427458
  -0.5144228 ]
 [ 1.26270023 -1.5409366   1.01170979 ... -0.6668221   0.21616
  -0.5144228 ]
 [-0.18232226  0.64895597  1.01170979 ...  0.97028605  2.13238916
  -0.5144228 ]
 ...
 [ 1.15154465  0.64895597  1.97748631 ... -0.6668221   0.21616
  -0.5144228 ]
 [ 1.3738558   0.64895597 -0.91984324 ... -0.6668221  -0.74195458
  -0.5144228 ]
 [ 0.59576677  0.64895597  1.01170979 ... -0.6668221  -0.74195458
  -0.5144228 ]]


In [14]:
from sklearn.linear_model import LogisticRegression
model_logistic = LogisticRegression()
model_logistic.fit(X_train,Y_train)

LogisticRegression()

In [15]:
from sklearn.svm import SVC
model_svm = SVC()
model_svm.fit(X_train,Y_train)

SVC()

In [16]:
from sklearn.neighbors import KNeighborsClassifier
model_kneighbors = KNeighborsClassifier()
model_kneighbors.fit(X_train,Y_train)

KNeighborsClassifier()

In [17]:
from sklearn.tree import DecisionTreeClassifier
model_tree = DecisionTreeClassifier()
model_tree.fit(X_train,Y_train)

DecisionTreeClassifier()

In [18]:
from sklearn.ensemble import RandomForestClassifier
model_random = RandomForestClassifier(n_estimators=1000)
model_random.fit(X_train,Y_train)

RandomForestClassifier(n_estimators=1000)

In [19]:
pip install xgboost

^C
Note: you may need to restart the kernel to use updated packages.


In [20]:
from xgboost import XGBClassifier
model_xg = XGBClassifier()
model_xg.fit(X_train,Y_train)

ModuleNotFoundError: No module named 'xgboost'

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
model_ada = AdaBoostClassifier(learning_rate=0.002, n_estimators=200, random_state=0)
model_ada.fit(X_train,Y_train)

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier 
model_extr =  ExtraTreesClassifier(n_estimators= 100)
model_extr.fit(X_train, Y_train)

In [ ]:
from sklearn.neural_network import MLPClassifier
model_mlp = MLPClassifier()
model_mlp.fit(X_train,Y_train)

In [ ]:
from sklearn.naive_bayes import BernoulliNB
model_nv =  BernoulliNB()
model_nv.fit(X_train, Y_train)

In [ ]:
x_test

In [ ]:
y_pred_logistic = model_logistic.predict(X_test)
y_pred_svm = model_svm.predict(X_test)
y_pred_kneighbors = model_kneighbors.predict(X_test)
y_pred_tree = model_tree.predict(X_test)
y_pred_random = model_random.predict(X_test)
y_pred_xg = model_xg.predict(X_test)
y_pred_ada = model_ada.predict(X_test)
y_pred_extr = model_extr.predict(X_test)
y_pred_mlp = model_extr.predict(X_test)
y_pred_nv = model_extr.predict(X_test)




In [ ]:
raw_data=dataset.sample(frac=0.25,random_state=1984)
raw_data.head()
raw_data_feat=raw_data.drop(columns=['target'])
raw_data_feat.head()


In [ ]:
print(y_pred_logistic)
print(y_pred_svm)

In [ ]:
filename= 'logistic_pred_model'
pickle.dump( model_logistic,open(filename,'wb'))

In [ ]:
loaded_model = pickle.load(open(filename,'rb'))
loaded_model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
logistic_Acc = accuracy_score(Y_test,y_pred_logistic)
SVM_Acc = accuracy_score(Y_test,y_pred_svm)
KNeighbors_Acc = accuracy_score(Y_test,y_pred_kneighbors)
DecTree_Acc = accuracy_score(Y_test,y_pred_tree)
Random_Acc = accuracy_score(Y_test,y_pred_random)
Xg_Acc = accuracy_score(Y_test,y_pred_xg)
Ada_Acc = accuracy_score(Y_test,y_pred_ada )
Extree_Acc = accuracy_score(Y_test,y_pred_extr)
Mlp_Acc = accuracy_score(Y_test,y_pred_mlp)
NaiveBase_Acc = accuracy_score(Y_test,y_pred_nv)

In [ ]:
print(logistic_Acc)
print(SVM_Acc)
print(KNeighbors_Acc)
print(DecTree_Acc)
print(Random_Acc)
print(Xg_Acc)
print(Ada_Acc)
print(Extree_Acc)
print(Mlp_Acc)
print(NaiveBase_Acc)

In [ ]:
plt.figure(figsize=(20,5))
plt.bar("logistic Regression",logistic_Acc)
plt.bar("Support Vector Mechine",SVM_Acc)
plt.bar("KNeighbors",KNeighbors_Acc)
plt.bar("DecesiNon Tree",DecTree_Acc)
plt.bar("Random Forest",Random_Acc)
plt.bar("Xboost",Xg_Acc)
plt.bar("Adaboost",Ada_Acc)
plt.bar("Extree",Extree_Acc)
plt.bar("Multi Layer Perceptron",Mlp_Acc)
plt.bar("NaiveBayes",NaiveBase_Acc)
plt.xlabel("Mechine Learning Algorithm")
plt.ylabel("Accuracy")

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
Y_test

In [ ]:
y_pred_logistic

In [ ]:
confusion_matrix(Y_test,y_pred_logistic)

In [ ]:
tn,fp,fn,tp=confusion_matrix(Y_test,y_pred_logistic).ravel()

In [ ]:
tn,fp,fn,tp

In [ ]:
logistic_specificity =tn/(tn+fp)

In [ ]:
print(logistic_specificity)

In [ ]:
logistic_errorrate=1-logistic_Acc
logistic_errorrate



In [ ]:
from sklearn.metrics import classification_report
print( classification_report(Y_test,y_pred_logistic))

In [ ]:
confusion_matrix(Y_test,y_pred_logistic)

In [ ]:
tn,fp,fn,tp=confusion_matrix(Y_test,y_pred_svm).ravel()

In [ ]:
tn,fp,fn,tp

In [ ]:
svm_specificity =93/(93+5)


In [ ]:
print(svm_specificity)

In [ ]:
SVM_errorrate=1-SVM_Acc
SVM_errorrate

In [ ]:
from sklearn.metrics import classification_report
print( classification_report(Y_test,y_pred_svm))

In [ ]:
confusion_matrix(Y_test,y_pred_kneighbors)

In [ ]:
tn,fp,fn,tp=confusion_matrix(Y_test,y_pred_kneighbors).ravel()

In [ ]:
tn,fp,fn,tp

In [ ]:
kneighbors_specificity =tn/(tn+fp)


In [ ]:
print(kneighbors_specificity)

In [ ]:
kneighbor_errorrate=1-KNeighbors_Acc
kneighbor_errorrate

In [ ]:
from sklearn.metrics import classification_report
print( classification_report(Y_test,y_pred_kneighbors))

In [ ]:
tn,fp,fn,tp=confusion_matrix(Y_test,y_pred_tree).ravel()

In [ ]:
tn,fp,fn,tp

In [ ]:
Dtree_specificity =tn/(tn+fp)

In [ ]:
print(Dtree_specificity)

In [ ]:
Dtree_errorrate=1-DecTree_Acc
Dtree_errorrate



In [ ]:
tn,fp,fn,tp=confusion_matrix(Y_test,y_pred_random).ravel()
tn,fp,fn,tp

In [ ]:
Random_specificity =tn/(tn+fp)
print(Random_specificity)

In [ ]:
Random_errorrate=1-Random_Acc
Random_errorrate

In [ ]:
tn,fp,fn,tp=confusion_matrix(Y_test,y_pred_xg).ravel()
tn,fp,fn,tp

In [ ]:
Random_specificity =tn/(tn+fp)
print(Random_specificity)

In [ ]:
tn,fp,fn,tp=confusion_matrix(Y_test,y_pred_ada).ravel()
tn,fp,fn,tp

In [ ]:
Ada_specificity =tn/(tn+fp)
print(Ada_specificity)

In [ ]:
tn,fp,fn,tp=confusion_matrix(Y_test,y_pred_extr).ravel()
tn,fp,fn,tp

In [ ]:
Etree_specificity =tn/(tn+fp)
print(Etree_specificity)

In [ ]:
tn,fp,fn,tp=confusion_matrix(Y_test,y_pred_mlp).ravel()
tn,fp,fn,tp

In [ ]:
Y_test,y_pred_nv

In [ ]:
tn,fp,fn,tp=confusion_matrix(Y_test,y_pred_nv).ravel()
tn,fp,fn,tp

In [ ]:
Naive_specificity =tn/(tn+fp)
print(Naive_specificity)

In [ ]:
confusion_matrix(Y_test,y_pred_nv)